import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'ui/screens/menu_screen.dart';
import 'services/analytics_service.dart';
import 'services/ad_service.dart';
import 'services/storage_service.dart';
import 'services/audio_service.dart';

/// Batch-20260107-153932-puzzle-01 - Generated by GameFactory
/// 
/// A Flutter + Flame mobile game with analytics, ads, and level progression.
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Lock orientation to portrait
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  
  // Initialize Firebase with error handling
  bool firebaseInitialized = false;
  try {
    await Firebase.initializeApp();
    firebaseInitialized = true;
  } catch (e) {
    if (kDebugMode) {
      print('Firebase not configured: $e');
    }
  }
  
  // Initialize services with error handling
  final analyticsService = AnalyticsService(firebaseEnabled: firebaseInitialized);
  final adService = AdService();
  final storageService = StorageService();
  final audioService = AudioService();
  
  await analyticsService.initialize();
  await adService.initialize();
  await storageService.initialize();
  await audioService.initialize();
  
  runApp(
    MultiProvider(
      providers: [
        Provider<AnalyticsService>.value(value: analyticsService),
        Provider<AdService>.value(value: adService),
        Provider<StorageService>.value(value: storageService),
        Provider<AudioService>.value(value: audioService),
      ],
      child: const GameApp(),
    ),
  );
}

/// Main application widget
class GameApp extends StatelessWidget {
  const GameApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Batch-20260107-153932-puzzle-01',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.dark,
        ),
      ),
      home: const MenuScreen(),
    );
  }
}
