/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Tile Tango',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.1,
      timeLimitSeconds: 60,
      targetScore: 5000,
      obstacleCount: 0,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 100,
      backgroundTheme: 'meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Gem Galore',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: 60,
      targetScore: 10000,
      obstacleCount: 0,
      obstacleSpeed: 0,
      collectibleCount: 15,
      collectibleValue: 200,
      backgroundTheme: 'crystal_cave',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Frozen Frenzy',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: 60,
      targetScore: 15000,
      obstacleCount: 5,
      obstacleSpeed: 1,
      collectibleCount: 20,
      collectibleValue: 150,
      backgroundTheme: 'winter_wonderland',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Lava Labyrinth',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.4,
      timeLimitSeconds: 45,
      targetScore: 20000,
      obstacleCount: 8,
      obstacleSpeed: 2,
      collectibleCount: 12,
      collectibleValue: 300,
      backgroundTheme: 'volcanic_island',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Enchanted Enigma',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 45,
      targetScore: 25000,
      obstacleCount: 10,
      obstacleSpeed: 1,
      collectibleCount: 15,
      collectibleValue: 400,
      backgroundTheme: 'mystical_forest',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Candy Chaos',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 45,
      targetScore: 30000,
      obstacleCount: 12,
      obstacleSpeed: 2,
      collectibleCount: 18,
      collectibleValue: 250,
      backgroundTheme: 'candy_land',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Neon Nightmare',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 30,
      targetScore: 35000,
      obstacleCount: 15,
      obstacleSpeed: 3,
      collectibleCount: 20,
      collectibleValue: 400,
      backgroundTheme: 'futuristic_city',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Spooky Scramble',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 30,
      targetScore: 40000,
      obstacleCount: 12,
      obstacleSpeed: 4,
      collectibleCount: 22,
      collectibleValue: 350,
      backgroundTheme: 'haunted_mansion',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Techno Takeover',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 30,
      targetScore: 45000,
      obstacleCount: 18,
      obstacleSpeed: 5,
      collectibleCount: 25,
      collectibleValue: 500,
      backgroundTheme: 'cyberpunk_city',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Cosmic Chaos',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 1.0,
      timeLimitSeconds: 30,
      targetScore: 50000,
      obstacleCount: 8,
      obstacleSpeed: 6,
      collectibleCount: 30,
      collectibleValue: 600,
      backgroundTheme: 'deep_space',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
